[package]
name = "lspsd"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
axum = "0.7.5"
ldk-node = { git = "https://github.com/johncantrell97/ldk-node", branch = "lsp-server" }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
