name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_DOWNLOAD: true
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
  windows-msvc-release:
    name: release windows msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cargo build --release
        env:
          SKIP_DOWNLOAD: true
      - name: zip
        run: zip -j archive.zip target/release/lspsd.exe
      - name: upload
        run: |
          $id = gh api -H "Accept: application/vnd.github+json" /repos/johncantrell97/lspsd/releases/tags/${{ github.ref_name }} --jq .id
          curl --fail-with-body -sS  -X POST --data-binary "@archive.zip" -H 'Content-Type: application/octet-stream' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "https://uploads.github.com/repos/johncantrell97/lspsd/releases/$id/assets?name=lspsd_${{ github.ref_name }}_x86_64-pc-windows-msvc.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos-arm-release:
    name: release mac os arm release
    runs-on: macos-12
    steps:
      - uses: actions/checkout@master
      - name: check toolchain
        run: rustup default
      - name: Build
        run: |
          rustup toolchain install stable-aarch64-apple-darwin
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
        env:
          SKIP_DOWNLOAD: true
      - name: zip
        run: zip -j archive.zip target/aarch64-apple-darwin/release/lspsd
      - name: upload
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" /repos/johncantrell97/lspsd/releases/tags/${{ github.ref_name }} --jq .id)
          curl --fail-with-body -sS  -X POST --data-binary @"archive.zip" -H 'Content-Type: application/octet-stream' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://uploads.github.com/repos/johncantrell97/lspsd/releases/$id/assets?name=lspsd_${{ github.ref_name }}_aarch64-apple-darwin.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}