name: Release

on:
  release:
    types: [created]

jobs:
  linux-release:
    name: release linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check toolchain
        run: rustup default
      - name: Build
        run: |
          rustup toolchain install stable-x86_64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
        env:
          SKIP_DOWNLOAD: true
      - name: zip
        run: zip -j archive.zip target/x86_64-unknown-linux-gnu/release/lspsd
      - name: upload
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" /repos/johncantrell97/lspsd/releases/tags/${{ github.ref_name }} --jq .id)
          curl --fail-with-body -sS  -X POST --data-binary @"archive.zip" -H 'Content-Type: application/octet-stream' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://uploads.github.com/repos/johncantrell97/lspsd/releases/$id/assets?name=lspsd-${{ github.ref_name }}-x86_64-unknown-linux-gnu.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos-arm-release:
    name: release mac os arm release
    runs-on: macos-14
    steps:
      - uses: actions/checkout@master
      - name: check toolchain
        run: rustup default
      - name: Build
        run: |
          rustup toolchain install stable-aarch64-apple-darwin
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
        env:
          SKIP_DOWNLOAD: true
      - name: zip
        run: zip -j archive.zip target/aarch64-apple-darwin/release/lspsd
      - name: upload
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" /repos/johncantrell97/lspsd/releases/tags/${{ github.ref_name }} --jq .id)
          curl --fail-with-body -sS  -X POST --data-binary @"archive.zip" -H 'Content-Type: application/octet-stream' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://uploads.github.com/repos/johncantrell97/lspsd/releases/$id/assets?name=lspsd-${{ github.ref_name }}-aarch64-apple-darwin.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
